sudo: required
language: generic

services:
  - docker

branches:
  only:
  - master

after_success:
  # Create images
  - docker build -t korzhynskiy/user-service-consumer -f ./UserService.Consumer/Dockerfile .
  - docker build -t korzhynskiy/user-service-api -f ./UserService.API/Dockerfile .
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker Hub
  - docker push korzhynskiy/user-service-consumer
  - docker push korzhynskiy/user-service-api

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: user-service
  env: UserService-env
  bucket_name: user-service-s3bucket
  bucket_path: user-service
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY