version: '3.4'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - '27018:27017'

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.11-2.0.1
    ports:
      - "9093:9093"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://:9093,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://:9093,EXTERNAL://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    restart: always

  gateway:
    image: korzhynskiy/gateway
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    depends_on:
      - kafka
    ports:
      - "3000:80"
    environment:
      MediatorSettings__BootstrapServers: kafka:9093
      Services__UserService__QueryUrl: http://query:80
      Services__UserService__GrpcUrl: http://querygrpc:80

  command:
    image: korzhynskiy/user-service-command
    build:
      context: .
      dockerfile: UserService.Command/Dockerfile
    depends_on:
      - kafka
    environment:
      MediatorSettings__BootstrapServers: kafka:9093
      MongoSettings__ConnectionString: mongodb://username:password@mongo:27017

  query:
    image: korzhynskiy/user-service-query
    build:
      context: .
      dockerfile: UserService.Query/Dockerfile
    environment:
      MongoSettings__ConnectionString: mongodb://username:password@mongo:27017
  
  querygrpc:
    image: korzhynskiy/user-service-querygrpc
    build:
      context: .
      dockerfile: UserService.Query.Grpc/Dockerfile
    environment:
      MongoSettings__ConnectionString: mongodb://username:password@mongo:27017
