apiVersion: skaffold/v1beta2
kind: Config
build:
    local:
        push: false 
    artifacts:
        - image: korzhynskiy/gateway
          context: .
          docker:
            dockerfile: Gateway/Dockerfile
        - image: korzhynskiy/user-service-command
          context: .
          docker:
            dockerfile: UserService.Command/Dockerfile
        - image: korzhynskiy/user-service-query
          context: .
          docker:
            dockerfile: UserService.Query/Dockerfile
deploy:
    kubectl:
        manifests:
            - k8s/command-deployment.yaml
            - k8s/gateway-deployment.yaml
            - k8s/query-deployment.yaml
            - k8s/gateway-cluster-ip-service.yaml
            - k8s/query-cluster-ip-service.yaml
