apiVersion: apps/v1
kind: Deployment
metadata:
    name: kafka-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            component: kafka
    template:
        metadata:
            labels:
                component: kafka
        spec:
            containers:
                - name: kafka
                  image: wurstmeister/kafka:2.11-2.0.1
                  ports:
                    - containerPort: 9092
                    - containerPort: 9093
                  env:
                    - name: KAFKA_ZOOKEEPER_CONNECT
                      value: zookeeper-cluster-ip-service:2181
                    - name: KAFKA_LISTENERS
                      value: INTERNAL://:9093,EXTERNAL://:9092
                    - name: KAFKA_ADVERTISED_LISTENERS
                      value: INTERNAL://kafka-cluster-ip-service:9093,EXTERNAL://kafka-cluster-ip-service:9092
                    - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
                      value: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
                    - name: KAFKA_INTER_BROKER_LISTENER_NAME
                      value: INTERNAL
             